ALTER TABLE routes
    ADD COLUMN IF NOT EXISTS origin           VARCHAR(100),
    ADD COLUMN IF NOT EXISTS destination      VARCHAR(100),
    ADD COLUMN IF NOT EXISTS status           VARCHAR(50)  DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS user_id          BIGINT,
    ADD COLUMN IF NOT EXISTS stations         TEXT,
    ADD COLUMN IF NOT EXISTS distance_km      INTEGER,
    ADD COLUMN IF NOT EXISTS estimated_minutes INTEGER,
    ADD COLUMN IF NOT EXISTS start_lat        DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS start_lon        DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS end_lat          DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS end_lon          DOUBLE PRECISION;
