server.port=8083
spring.application.name=ktz-history
spring.kafka.bootstrap-servers=kafka:9092

spring.datasource.url=jdbc:postgresql://postgres:5432/ktz
spring.datasource.username=ktz
spring.datasource.password=ktz
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true





# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html