server:
  port: ${SERVER_PORT}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_USER}
  secret-key: ${MINIO_PASSWORD}
  bucket: ${MINIO_BUCKET}

spring:
  application:
    name: ktz-gateway
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://postgres:5432/ktz}
    username: ${POSTGRES_USER:ktz}
    password: ${POSTGRES_PASSWORD:ktz}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    gateway:
      routes:
        - id: simulator
          uri: http://simulator:${SIMULATOR_PORT}
          predicates:
            - Path=/simulator/**
          filters:
            - StripPrefix=1

        - id: telemetry
          uri: http://telemetry:${TELEMETRY_PORT}
          predicates:
            - Path=/telemetry/**
          filters:
            - StripPrefix=1

        - id: history
          uri: http://history:${HISTORY_PORT}
          predicates:
            - Path=/history/**
          filters:
            - StripPrefix=1

        - id: swagger-webjars
          uri: http://telemetry:${TELEMETRY_PORT}
          predicates:
            - Path=/webjars/**

        - id: simulator-docs
          uri: http://simulator:${SIMULATOR_PORT}
          predicates:
            - Path=/simulator/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: telemetry-docs
          uri: http://telemetry:${TELEMETRY_PORT}
          predicates:
            - Path=/telemetry/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: history-docs
          uri: http://history:${HISTORY_PORT}
          predicates:
            - Path=/history/v3/api-docs/**
          filters:
            - StripPrefix=1

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: simulator
        url: /simulator/v3/api-docs
      - name: telemetry
        url: /telemetry/v3/api-docs
      - name: history
        url: /history/v3/api-docs
  api-docs:
    enabled: true