server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ktz-simulator
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

telemetry:
  frequency-hz: ${TELEMETRY_FREQUENCY_HZ}
  locomotives:
    - number: ${LOCO_1_NUMBER}
      type: ${LOCO_1_TYPE}
      name: ${LOCO_1_NAME}
    - number: ${LOCO_2_NUMBER}
      type: ${LOCO_2_TYPE}
      name: ${LOCO_2_NAME}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html