server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ktz-simulator
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

telemetry:
  frequency-hz: ${TELEMETRY_FREQUENCY_HZ}
  locomotives:
    - number: ${LOCO_1_NUMBER}
      type: ${LOCO_1_TYPE}
      name: ${LOCO_1_NAME}
      start-lat: ${LOCO_1_START_LAT:51.18}
      start-lon: ${LOCO_1_START_LON:71.45}
      end-lat: ${LOCO_1_END_LAT:53.31}
      end-lon: ${LOCO_1_END_LON:69.39}
    - number: ${LOCO_2_NUMBER}
      type: ${LOCO_2_TYPE}
      name: ${LOCO_2_NAME}
      start-lat: ${LOCO_2_START_LAT:43.25}
      start-lon: ${LOCO_2_START_LON:76.93}
      end-lat: ${LOCO_2_END_LAT:42.30}
      end-lon: ${LOCO_2_END_LON:69.60}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html